version: "3.7"

networks:
  local-net:
    external: true

services:
  node-app:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./:/usr/src/app
    environment:
      - DOCKER_BUILD_MODE=development
    command: npm run dev
